### ISSUE TITLE
Broken links in the setup section

### ISSUE THREAD

**Issue by fabel134** [carpentries-lab/metagenomics-workshop#19]
I was trying to download the files 'yml' for setting an environment but the next links are broken:

https://github.com/carpentries-lab/metagenomics/blob/gh-pages/files/spec-file-Ubuntu22.txt
https://github.com/carpentries-lab/metagenomics/blob/gh-pages/files/metagenomics-Ubuntu22.yml

I found the broken links in the Setup section:  https://carpentries-lab.github.io/metagenomics-workshop/setup.html

**Comment by Czirion** [comment]
Thank you Abel
I fixed those links and found others with the same problem and fixed them all.
